### ISSUE TITLE
 practica de predicados cuantificadores

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-equipo-saul-lopez-bautista#1]
[Practica de Predicados, cuantificadores.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-equipo-saul-lopez-bautista/files/7522820/Practica.de.Predicados.cuantificadores.pdf)

**Comment by irving1613** [comment]
Muy buen trabajo cumple con todo lo señalado en la rubrica, esta bien resuelto y completo.
30 Puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado.

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by josealfredo79** [comment]
Bien hecho y revisado
