### ISSUE TITLE
Practica de predicados y cuantificadores

### ISSUE THREAD

**Issue by RicardoMtzSts** [SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-equipo-saul-lopez-bautista#3]
[Practica de predicados y cuantificadores.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-equipo-saul-lopez-bautista/files/7548675/Practica.de.predicados.y.cuantificadores.pdf)

**Comment by yanet02** [comment]
Portada (25%)
Procedimiento(22%) faltó la descripción y resultados.
Figuras, ilustraciónes y fotografías(25%) 
Resultados y conclusiónes(22%)  faltó resultados.
Total = 94%
Calificación=28.8%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
